typography_spectrum: 0.652310447068885
color:
  brandColors:
    - '#808080'
    - '#414141'
    - '#b3b3b3'
    - '#030303'
    - '#d8d8d8'
  brandStrength: 0.1875
  lightness: 0.5774333809968084
  saturation: 0.39505929267033935
  rhythmicContrast: 0.9105432846117765
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Travis HEllstrom
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Travis Hellstrom
description: Helping You Lead a Happy Simple Life
purpose: []
